[package]
name = "kidz5/kidzuix3"
description = "KIDzUIx3 — a Luau UI library by KIDz based on macOS Sequoia."
license = "MIT"
authors = ["KIDz"]
version = "1.0.0"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = [
    "src/*",
    "default.project.json",
    "wally.lock",
    "wally.toml",
    "README.md",
    "LICENSE",
]

[dependencies] # Im not sure if wally handles packages correctly, so im not gonna recommend to use wally installation method. Plus i dont feel like updating this every time.
Fusion = "elttob/fusion@^0.3"